Export line numbers in SpinJa error trails + update command line arguments

diff --git a/src/scripts/spinjal.in b/src/scripts/spinjal.in
--- a/src/scripts/spinjal.in
+++ b/src/scripts/spinjal.in
@@ -11,61 +11,46 @@ LTSMIN_LIB="@pkglibdir@"
 
 spinja_dir="$LTSMIN_PREFIX/share/ltsmin"
 
-show_usage=
+CP="$spinja_dir/spinja.jar"
 promela_file=
-gcc_options=
+no_compile=0
 
-if [ $# -eq 0 ] ; then
-    echo "usage: spinja [gcc_options] promela_file" ;
+for option in ${1+"$@"}; do
+    if [ "${option:0:2}" == "-I" ]; then
+        no_compile=1
+    elif [ "${option:0:1}" != "-" ]; then
+        promela_file="$option"
+    fi
+done
+
+if [ -z "$promela_file" ]; then
+    echo "usage: spinja [options] promela_file" ;
     echo "options will be passed to GCC"
     exit 1
 fi
 
-VERBOSE=0
-promela_file=
-while (( $# > 0 )); do
-    if [ "$1" == "-s" ]; then
-        SKIP_SPINJA="1";
-    elif [ "${1}" == "-v" ]; then
-        OPTIONS="$OPTIONS $1"
-        VERBOSE=1
-    elif [ "${1:0:1}" == "-" ]; then
-        OPTIONS="$OPTIONS $1"
-    else
-		promela_file=$1
-    fi
-    shift;
-done
-
-#while [ $# -gt 1 ] ; do
-#    gcc_options="$gcc_options $1"
-#    shift
-#done
-
 promela_name=`basename $promela_file`
 output_file="${promela_name}.spinja.c"
 
-if [ "$SKIP_SPINJA" != "1" ]; then
-	if [ -f "$output_file" ]; then
-		rm -f "$output_file";
-	fi
-	
-	java -Xms120m -ea:spinja... -Xmx2048m -cp "$spinja_dir/spinja.jar" spinja.Compile -l $OPTIONS $promela_file
-	ERROR=$?
-    if [ $ERROR -ne 0 ]; then
-		echo "Compilation of $promela_file failed"
-		exit $ERROR;
-	fi
-else
-	echo "Skipping compilation...";
+if [ -f "$output_file" ]; then
+    rm -f "$output_file";
 fi
 
-gcc -pthread -fPIC -shared $output_file -o $promela_name.spinja -O0 -g $gcc_options
-if [ $VERBOSE = 1 ]; then
-    echo gcc -pthread -fPIC -shared $output_file -o $promela_name.spinja -O0 -g $gcc_options
+java -Xms120m -Xmx2048m -cp $CP spinja.Compile -l ${1+"$@"}
+ERROR=$?
+if [ $ERROR -ne 0 ]; then
+    echo "Compilation of $promela_file failed"
+    exit $ERROR;
 fi
+
+if [ $no_compile == 1 ]; then
+    echo
+    exit 0
+fi
+
+gcc -fPIC -shared -O2 -ggdb $CFLAGS $output_file -o $promela_name.spinja
 if [ ! $? -eq 0 ]; then
-	echo "Compilation of $output_file failed"
+    echo "Compilation of $output_file failed"
 else
-	echo "Compiled C model to $promela_name.spinja"
+    echo "Compiled C model to $promela_name.spinja"
 fi
