ltsmin_open for mCRL, mCRL2 (tested) and ETF, NIPS-VM (not tested)

diff --git a/src/ltsmin_open.in b/src/ltsmin_open.in
--- a/src/ltsmin_open.in
+++ b/src/ltsmin_open.in
@@ -34,70 +34,71 @@ LTSMIN_PREFIX=$prefix
 exec_prefix=@exec_prefix@
 datadir=@datadir@
 top_srcdir=@top_srcdir@
-LTSMIN_LIB=${exec_prefix}/src
-#  ../buddy/src/libbdd.a
-LTSMIN_LD_FLAGS="-L$LTSMIN_LIB ltsminopen -lutil -lz -lpopt  @MCRL_LDFLAGS@  -lstep -lmcrl -lmcrlunix -lATerm -ldl -L$BIN -lBCG_IO -lBCG -lm  -rdynamic"
+LTSMIN_LIB=@libdir@
 
 # phase 1: parsing the options
 
 LTSMIN_OPTIONS=""
-export LTSMIN_OPTIONS
-
 while true
 do
 	if test $# -lt 1
 	then
-		echo "$COMMAND: missing \`\`.tbf'' filename argument"
+		echo "$COMMAND: missing model argument"
 		exit 1
 	fi
 	case $1 in
-		-version )
-			echo $LTSMIN_VERSION
-			exit 0
-			;;
-                -help )
-		        cat $datadir/README_mcrl_open
-			exit 0
-                        ;;
-		-alt | -confluent )
-			if test $# -le 2
-			then
-				echo "$COMMAND: missing value for option $1"
-				exit 1
-			fi
-			LTSMIN_OPTIONS="$LTSMIN_OPTIONS $1 $2"
-			shift 2
-			;;	
-		-* )
-			LTSMIN_OPTIONS="$LTSMIN_OPTIONS $1"
-			shift 1
-			;;
-		* )
-			break
-			;;
-	esac
+        -* )
+            LTSMIN_OPTIONS="$LTSMIN_OPTIONS \"$1\""
+            shift 1
+            ;;
+        * )
+            break
+        ;;
+    esac
 done
+export LTSMIN_OPTIONS
 
 # phase 2: parsing the TBF filename (TODO: the value of $FILE may contain spaces)
 
-FILE=`dirname "$1"`/`basename "$1" .tbf`
-shift
-
-if test ! -f "$FILE.tbf"
+FILE=$1
+if test ! -f "$FILE"
 then
-	echo "$COMMAND: file \`\`$FILE.tbf'' does not exist"
+	echo "$COMMAND: file \`\`$FILE'' does not exist"
 	exit 1
 fi
+case $FILE in
+ *tbf)
+    if test "@MCRL_LDFLAGS@" == "\@MCRL_LDFLAGS\@" ; then
+        echo "mCRL is not supported"
+        exit 1
+    fi
+    echo "input is mCRL"
+    LTSMIN_LD_FLAGS="@MCRL_LDFLAGS@ -L$LTSMIN_LIB @CADP_LDFLAGS@ -llpo-open -lutil @MCRL_LIBS@ @CADP_LIBS@ -lz -lpopt"
+    ;;
+ *lps)
+    if test "@MCRL2_LDFLAGS@" == "\@MCRL2_LDFLAGS\@" ; then
+        echo "mCRL2 is not supported"
+        exit 1
+    fi
+    echo "input is mCRL2"
+    LTSMIN_LD_FLAGS="@MCRL2_LDFLAGS@ -L$LTSMIN_LIB @CADP_LDFLAGS@ -llps-open -lutil @MCRL2_LIBS@ @CADP_LIBS@ -lz -lpopt"
+    ;;
+ *)
+    echo "Did not recognize type of $FILE"
+    exit 1
+    ;;
+esac
+shift
 
 # phase 3: passing the TBF filename to the C library
 
-OPEN_CAESAR_FILE="$FILE.tbf"
+OPEN_CAESAR_FILE="$FILE"
 export OPEN_CAESAR_FILE
 
 # phase 4: parsing the options for cc(1) and preparing other options
 
 CPPFLAGS="-I. -I$CADP/incl -I$SRC"
-CFLAGS=""
+CFLAGS="@CFLAGS@"
 LDFLAGS="$LTSMIN_LD_FLAGS -L$CADP/bin.$ARCH -lcaesar -lm"
 
 while true
@@ -265,9 +266,9 @@ echo "LD_LIBRARY_PATH_AUX=$LD_LIBRARY_PATH_AUX"
 
 if test "$#" -eq 0
 then
-	echo "$COMMAND: running \`\`$PROG'' for \`\`$FILE.tbf''"
+	echo "$COMMAND: running \`\`$PROG'' for \`\`$FILE''"
 else
-	echo "$COMMAND: running \`\`$PROG $@'' for \`\`$FILE.tbf''"
+	echo "$COMMAND: running \`\`$PROG $@'' for \`\`$FILE''"
 fi
 ./$PROG "$@"
 
